### Numpy array

# 

In [1]:
import  numpy as  np

In [2]:
l  =  [12 ,23 , 45,65]
ar1  =  np.array(l)

In [3]:
ar1

array([12, 23, 45, 65])

In [4]:
type(ar1)

numpy.ndarray

In [ ]:
# some  functions  on array
- ndim
- size
-  shape
-  type

In [5]:
ar1.shape

(4,)

In [6]:
ar1.size

4

In [7]:
ar1.ndim

1

In [9]:
ar1.dtype

dtype('int64')

In [11]:
ar2  =  np.array([12,45,56.34  ,45.8])
ar2

array([12.  , 45.  , 56.34, 45.8 ])

In [12]:
ar2

array([12.  , 45.  , 56.34, 45.8 ])

In [ ]:
print(ar2.ndim  )
print(ar2.size)
print(ar2.shape)
ar2.dtype   # array contain  homogenous  data type

1
4
(4,)


dtype('float64')

In [19]:
## craete  2d array
l1 =  [[10 ,20 ,30 ] ,  [40 , 50 , 60 ]]
array2d =  np.array(l1)


In [20]:
array2d

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
array2d.ndim

2

In [22]:
array2d.shape

(2, 3)

In [23]:
l2  =  [[[10 ,20 , 30] ,  [40 , 50 , 60]] ,  [[70 , 80 , 90] ,  [100 , 110 , 120]]]

In [24]:
array4  =  np.array(l2)

In [25]:
array4

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [26]:
array4.shape

(2, 2, 3)

In [56]:
l2  =  [[[10 ,20 ], [30 ,  40 ],[ 50 , 60]] ,  [[70 , 80] ,[ 90 ,  100] ,[ 110 , 120]]]

In [57]:
array5 = np.array(l2)

In [59]:
array5

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]]])

In [60]:
array5.shape

(2, 3, 2)

In [72]:
l2  =  [[[[10 ,20 ], [30 ,  40 ]] ,  [[70 , 80] ,[ 90 ,  100]]  ] ,  
[[[10 ,20 ], [30 ,  40 ]] ,  [[70 , 80] ,[ 90 ,  100]]  ]]

In [73]:
array6 =  np.array(l2)

In [75]:
array6

array([[[[ 10,  20],
         [ 30,  40]],

        [[ 70,  80],
         [ 90, 100]]],


       [[[ 10,  20],
         [ 30,  40]],

        [[ 70,  80],
         [ 90, 100]]]])

In [74]:
array6.shape

(2, 2, 2, 2)

In [52]:
# create 4d array shape  2,2,2,2
l3  =  [[[[10  , 20 ] ,  [30 , 40]]],[ [ [50 , 60] ,  [70 , 80]] ]]
array6  =  np.array(l3)

In [53]:
array6

array([[[[10, 20],
         [30, 40]]],


       [[[50, 60],
         [70, 80]]]])

In [54]:
array6.shape

(2, 1, 2, 2)

In [55]:
array6[0]


array([[[10, 20],
        [30, 40]]])

In [ ]:
l2  =  [[[10 ,20 ], [30 ,  40 ],[ 50 , 60]] ,  [[70 , 80] ,[ 90 ,  100] ,[ 110 , 120]], [[130  , 140] ,  [] ]]

In [71]:
array7 = np.array(l2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [76]:
# indexing  

In [77]:
ar1

array([12, 23, 45, 65])

In [78]:
ar1[0]

np.int64(12)

In [79]:
ar1[1]

np.int64(23)

In [80]:
ar1[-1]

np.int64(65)

In [81]:
ar1[3]

np.int64(65)

In [82]:
array2d

array([[10, 20, 30],
       [40, 50, 60]])

In [86]:
array2d.shape

(2, 3)

In [89]:
print(array2d[0])
print(array2d[1])
print(array2d[: ,  2])


[10 20 30]
[40 50 60]
[30 60]


In [90]:
array2d

array([[10, 20, 30],
       [40, 50, 60]])

In [91]:
array2d[1 ,  2]

np.int64(60)

In [92]:
array2d[1 , :]

array([40, 50, 60])

In [94]:
array2d[0:2 ,  0:2]

array([[10, 20],
       [40, 50]])

In [95]:
array2d[0:2 , 0:1]

array([[10],
       [40]])

In [105]:
ar6 =  np.array([12,13,14,15,16])
ar7  =  np.array((17 , 18 , 19 , 20 , 21))
x  =  [12,13,14,15,16]
y =  [17 , 18 , 19 , 20 , 21]

In [97]:
l+ 10

TypeError: can only concatenate list (not "int") to list

In [98]:
ar6+10

array([22, 23, 24, 25, 26])

In [99]:
ar6*2

array([24, 26, 28, 30, 32])

In [100]:
ar6/2

array([6. , 6.5, 7. , 7.5, 8. ])

In [101]:
ar6**2

array([144, 169, 196, 225, 256])

In [102]:
ar6//2

array([6, 6, 7, 7, 8])

In [103]:
ar6%2

array([0, 1, 0, 1, 0])

In [106]:
x+ y

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [107]:
ar6+ar7

array([29, 31, 33, 35, 37])

In [108]:
x/y

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [109]:
ar6/ar7

array([0.70588235, 0.72222222, 0.73684211, 0.75      , 0.76190476])

In [110]:
ar6*ar7

array([204, 234, 266, 300, 336])

In [111]:
ar6//ar7

array([0, 0, 0, 0, 0])

In [112]:
ar6**ar7

array([2218611106740436992, 1774942509700083433, -441120932980326400,
       4664335276710460609,                   0])

In [113]:
ar6%ar7

array([12, 13, 14, 15, 16])

### functions  on unsing  numpy library
mean
max
min
square
sqrt
cbrt
round
sum  
abs
log
exp


In [114]:
l

[12, 13, 14, 15, 16]

In [115]:
np.sum(l)

np.int64(70)

In [116]:
np.sum(ar1)

np.int64(145)

In [117]:
print(l  , ar1)

[12, 13, 14, 15, 16] [12 23 45 65]


In [118]:
print(np.max(l) ,  np.max(ar1))
print(np.min(l) ,  np.min(ar1))
print(np.mean(l) ,  np.mean(ar1))


16 65
12 12
14.0 36.25


In [122]:
l  =  [1.26646, 13.433443, 1.4343, 15.88998, 16]
np.round(l)
np.round(l ,  2)

array([ 1.27, 13.43,  1.43, 15.89, 16.  ])

In [123]:
np.square(23)

np.int64(529)

In [124]:
np.square(l)

array([  1.60392093, 180.45739083,   2.05721649, 252.4914644 ,
       256.        ])

In [125]:
np.sqrt(l)

array([1.12537105, 3.66516616, 1.19762265, 3.98622378, 4.        ])

In [126]:
np.cbrt(l)

array([1.08192501, 2.37718207, 1.12775129, 2.51405312, 2.5198421 ])

In [129]:
np.exp(32)


np.float64(78962960182680.69)

In [130]:
l

[1.26646, 13.433443, 1.4343, 15.88998, 16]

In [128]:
np.exp(l)

array([3.54826943e+00, 6.82448947e+05, 4.19670629e+00, 7.96032193e+06,
       8.88611052e+06])

In [131]:
np.log(l)

array([0.23622561, 2.59774734, 0.36067693, 2.76568872, 2.77258872])

In [132]:
np.log(2.71)

np.float64(0.9969486348916096)

In [133]:
np.log(0)

C:\Users\admin\AppData\Local\Temp\ipykernel_13552\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


np.float64(-inf)

In [134]:
np.log(1)

np.float64(0.0)

In [136]:
l  = [-1.26646, -13.433443, -1.4343, 15.88998, 16]

In [137]:
np.abs(l)

array([ 1.26646 , 13.433443,  1.4343  , 15.88998 , 16.      ])

## trignometric operations 
- sin
- cos
- tan 
- radiance

In [138]:
angle  =  [0 , 30 , 45, 60 , 90]
np.sin(angle)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [139]:
np.cos(angle)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [140]:
np.tan(angle)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

In [ ]:
np.cot(angle)

AttributeError: module 'numpy' has no attribute 'cot'

In [142]:
1/np.cos(angle)

array([ 1.        ,  6.48292123,  1.90359441, -1.04996469, -2.23177613])

In [147]:
np.radians(angle)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [148]:
l

[-1.26646, -13.433443, -1.4343, 15.88998, 16]

In [149]:
np.prod(l)

np.float64(-6203.862248140924)

In [150]:
np.std(l)

np.float64(11.339850888627268)

In [151]:
np.var(l)

np.float64(128.59221817630063)

### Generate data using numpy

In [152]:
range(1 , 11)  # it  is used to generate integers  only

range(1, 11)

In [153]:
range( 1, 22.3)

TypeError: 'float' object cannot be interpreted as an integer

In [154]:
#  arange  is used to generate  both  int and float

In [156]:
np.arange(1 ,  11 , 2)

array([1, 3, 5, 7, 9])

In [157]:
np.arange(1 ,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
np.arange(1 , 100  ,  0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5,
       34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. ,
       39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5,
       45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. ,
       50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5, 55. , 55.5,
       56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. , 60.5, 61. ,
       61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5, 66. , 66.5,
       67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. , 71.5, 72. ,
       72.5, 73. , 73.5, 74. , 74.5, 75. , 75.5, 76

In [160]:
np.arange(100  , 50  ,  -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51])

In [161]:
np.arange(100  , 50  ,  -3.5)

array([100. ,  96.5,  93. ,  89.5,  86. ,  82.5,  79. ,  75.5,  72. ,
        68.5,  65. ,  61.5,  58. ,  54.5,  51. ])

####  linspace  for  generating  linearly scaping data

In [162]:
np.linspace(1 , 20,  100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [163]:
19.42424242-       19.23232323, 

(0.19191919000000013,)

In [164]:
19.61616162- 19.42424242

0.19191920000000096

In [166]:
np.linspace(1 , 20,  100 ,  retstep = True)

(array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
         2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
         4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
         6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
         8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
        10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
        12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586, 14.0